# Generated by Django 5.2 on 2025-04-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Mountains', 'Mountains'), ('Beaches', 'Beaches'), ('Wildlife', 'Wildlife'), ('Historical Attractions', 'Historical Attractions')], max_length=100, unique=True),
        ),
    ]
